### PR TITLE
Newreg

### PR DESCRIPTION
**Pull request by gwmdsi**
See the report draft update. I've written up most of my EDA and analysis, plus added a partial objective and commit history for collaboration evidence.

May be a problem with file conflict - let's see

### CODE REVIEW

**Comment by gwmdsi** [comment]
The conflict is showing the whole notebook conflicts between the two, as if it is a complete replacment - not sure why. I took Adrian's most recent branch, merged to master, removed a big slab of my section and copied in a new version of that part which I'd been working on in another book.

**Comment by svetlana2113** [comment]
@gwmdsi it shows a problem with python file, as if conflicting the latest master - but i just looked through the file from Adrian's commit (that was including all previous work) and your file, and can't see what's wrong with your file, previous code from master is there. I think we can try to merge/overwrite master file

**Comment by gwmdsi** [comment]
yeah, I went through cell by cell and can't work it out. Also when use conflict resolution on github it just shows whole file as one block. Adrian doesn't appear to be on yet, so I suggest you merge it so you can keep working. If there is a problem with file operation when you pull it, we can restore previous version. Also if Adrian notices anything missing later today he can add/remove cells, as any difference must be minor.

**Comment by svetlana2113** [comment]
Yes, I also compared the two file, from Adrian and from this commit - can't see what's wrong here
As i mentioned on slack, i can only guess the problem is caused when commits are submitted from different types of machines i.e. from Mac or PC (when previous file was from Mac and now a commit is from PC it probably re-writes everything, then if you make next commit from Mac again same thing will happen, etc.)

Ok, i'll try to merge now

**Review by svetlana2113 — APPROVED** [review]

**Pull request merged**
